---
- name: AWS Scripting
  hosts: localhost
  connection: local
  # secrets.yml file stores aws credentials
  # varfile.yml stores required variables
  vars_files:
    - vars/varsfile.yml
    - vars/aws-creds.yml
  environment:
    - ansible_python_interpreter: /usr/bin/python3.8
    - AWS_ACCESS_KEY_ID: "{{ myuser }}"
    - AWS_SECRET_ACCESS_KEY: "{{ mykey }}"
    - AWS_REGION: "{{ region }}"
  gather_facts: false

  tasks:
  - name: Get AWS info
    block:
    - name: Get Running instance Info
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": Wordpress
      register: ec2info
    
    - name: get ami info
      ec2_ami_info:
        filters:
          "tag:env": "{{ ami_mode }}"
      register: ami_info

    - name: get elb info
      ec2_elb_info:
        Name: "{{ lb_name }}"
      register: elb_info

    tags: ['always', 'get-info'] 

  - name: Create Bucket
    block:
    - name: Create an empty bucket
      aws_s3:
        bucket: "{{ s3_bucket_name }}"
        mode: create
        region: "{{ region }}"
    tags: ['never', 'create-bucket']


  - name: AMI creation
    block:
    - name: Create AMI
      ec2_ami:
        instance_id: "{{ ec2info.instances.instance_id }}"
        wait: no
        name: "{{ ami_name }}"
        tags:
          env: "{{ ami_mode }}"
      register: ami_info
    tags: ['never', 'create_ami']
  
  - name: Achieve HA for {{ ami_name }} 
    block:
    - name: create launch config
      ec2_lc:
        name: "{{ lc_name }}"
        image_id: "{{ ami_info.image_id }}"
        key_name: "{{ keyname }}"
        region: "{{ region }}"
        security_groups: "{{ ec2info.instances.groups.group_id }}"
        instance_type: t2.micro
        user_data: |
          #!/bin/bash
          sudo apt update -y
          aws s3 sync --delete s3://<bucker-name> /var/www/html
        assign_public_ip: yes
        volumes:
        - device_name: /dev/sda1
          volume_size: 8
          delete_on_termination: true

      register: lc_info
    - name: Creating autoscaling group
      ec2_asg:
        name: "{{ asg_name }}"
        launch_config_name: "{{ lc_info.name }}"
        load_balancers: "{{ lb_name }}"
        health_check_period: 60
        health_check_type: ELB
        replace_all_instances: yes
        min_size: 1
        max_size: 3
        desired_capacity: 2
        region: "{{ region }}"
    tags: ['never', 'make-ha']