- hosts: all
  gather_facts: False
  become: yes
  connection: ssh
  vars_files:
    - vars/default.yml
  tasks:
    - name: Installing AWS-CLI
      apt: name=awscli state=latest

    - name: Restart NGINX
      systemd: name=nginx state=restarted enabled=yes

    - name: Read Node
      block:
      - name: cron job for backing up wp code to s3
        cron:
          name: "EC2 to s3"
          job: " aws s3 sync --delete {{ s3_bucket_url_code }} /var/www/html/wordpress"
      tags: ['never','read-node']

    - name: Write Node
      block:
      - name: cron job for backing up wp code to s3
        cron:
          name: "EC2 to s3"
          job: " aws s3 sync --delete /var/www/html/wordpress {{ s3_bucket_url_code }}"
      tags: ['never','write-node']