- hosts: all
  gather_facts: False
  become: yes
  connection: ssh
  vars_files:
    - vars/default.yml
  roles:
     - upgrade      
     - nginx
     - php 
# remove # in below line to install db inside instance only i.e. to deploy LEMP stack
#     - mysql
     - wordpress